services:
  qdrant:
    image: qdrant/qdrant # Specifies the Qdrant image to use
    # container_name: qdrant # Sets the container name to qdrant
    ports:
      - "6333:6333" # Maps port 6333 on the host to port 6333 in the container
    volumes:
      - qdrant_data:/qdrant/storage # Mounts the qdrant_data volume to /qdrant/storage in the container

  pgvector:
    # image: "postgres:16-bullseye"
    image: pgvector/pgvector:pg16-trixie
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_USER: root
      POSTGRES_DB: rag
      # NOTE: for nomic-embed-text
      EMBEDDING_SIZE: 768
      # NOTE: for Qwen3-Embedding-8B
      # EMBEDDING_SIZE: 4096
    volumes:
      - pg_data:/var/lib/postgresql
      - ./db/init-vector.sh:/docker-entrypoint-initdb.d/init-vector.sh
    secrets:
      - db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web_ai:
    build:
      context: ./web # Specifies the build context as the ./app directory
      dockerfile: Dockerfile # Uses the Dockerfile in the build context
    tty: true
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ..
          target: /app
        - action: rebuild
          path: ../requirements.txt
    environment:
      DB_PASSWORD_FILE: /run/secrets/db-password
      DB_USER: root
      DB_NAME: rag
      DB_HOST: pgvector
      QDRANT_CLIENT: http://qdrant:6333
      OLLAMA_URL: http://ollama:11434
    ports:
      - 8000:8000
    secrets:
      - db-password
    depends_on:
      - qdrant # Ensures the qdrant service is started before winy
      - pgvector # Ensures the qdrant service is started before winy
      - ollama # Ensures the ollama service is started before winy

  ollama:
    image: ollama/ollama # Specifies the Ollama image to use
    ports:
      - "11434:11434" # Maps port 11434 on the host to port 11434 in the container
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_MODELS=/usr/share/ollama/.ollama/models
    healthcheck:
      test: "ollama --version && ollama ps || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ollama-models:/usr/share/ollama/.ollama/models
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia # Specifies the driver to use for GPU
    #           count: 1 # Reserves 1 GPU
    #           capabilities: [gpu] # Specifies that the device capability is GPU

volumes:
  qdrant_data: # Defines the qdrant_data volume
  pg_data: {}
  ollama-models:

secrets:
  db-password:
    file: ./secrets/password.txt

